flask_website/__init__.py
from flask import Flask
from flask_login import LoginManager

login_manager = LoginManager()
app = Flask(__name__)

flask_website/views/admin.py
from flask import Blueprint, request, render_template, flash, redirect, url_for
from flask_login import login_user, login_required, logout_user
from flask_website.user import User
from flask_website import login_manager
from flask_website.config import admin_id, admin_username,admin_password

admin = Blueprint('admin', __name__)


@admin.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':

        username = request.form['username']
        password = request.form['password']
        if username == admin_username and password == admin_password:
            user = User(admin_id, admin_username, admin_password)
            login_user(user)
            return redirect(url_for('admin.index'))
        else:
            flash('Invalid username or password!', category='danger')
    return render_template('admin/login.html')


@admin.route('/index')
@login_required
def index():
    return render_template('admin/index.html')


@admin.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('general.index'))


@login_manager.unauthorized_handler
def unauthorized_handler():
    flash('Please login first!', category='danger')
    return redirect(url_for('admin.login'))


@login_manager.user_loader
def load_user(id):
    return User.get_by_id(id)

flask_website/views/chat.py
# import time
# from threading import Timer

from flask import Blueprint, render_template, request, jsonify, session

# from flask_website.config import disconnect_after_not_post_back
from flask_website.im import xiaoice_storage

chat = Blueprint('chat', __name__)

# last_im_time = {}


@chat.route('/index')
def index():
    return render_template('chat.html')


@chat.route('/handshake', methods=['POST'])
def handshake():

    # second request
    if 'client_id' in session:
        return jsonify(retCode='1', msg='Hello, I am here!')

    # first request
    client_id = xiaoice_storage.get_avail_xiaoice_client_id()
    if client_id is not None:
        session['client_id'] = client_id
        return jsonify(retCode='0', msg='Hello, I am xiaoice!')

    return jsonify(retCode='-1', msg='Xiaoice is busy!')


@chat.route('/message', methods=['POST'])
def message():
    post_data = request.get_json()
    msg = post_data['msg']
    xiaoice = xiaoice_storage.get_xiaoice_by_client_id(session['client_id'])
    xiaoice.send_msg(msg)
    return jsonify(retCode='0', msg=msg)


@chat.route('/im', methods=['POST'])
def im():

    # client_id = session['client_id']
    # last_im_time[client_id] = time.time()
    xiaoice = xiaoice_storage.get_xiaoice_by_client_id(session['client_id'])

    msg = xiaoice.get_msg()

    # timer = Timer(disconnect_after_not_post_back, check_im_alive, args=(client_id,))
    # timer.start()

    return jsonify(retCode='0', msg=msg)


# def check_im_alive(client_id):
#     last_connect_time = last_im_time[client_id]
#     now = time.time()
#     if now - last_connect_time > disconnect_after_not_post_back:
#         del last_im_time[client_id]
#         xiaoice_storage.free_xiaoice_by_client_id(client_id)

flask_website/views/general.py
from flask import Blueprint, redirect, url_for

general = Blueprint('general', __name__)


@general.route('/')
def index():
    return redirect(url_for('chat.index'))

flask_website/views/xiaoice.py
import logging
from threading import Thread

from flask import Blueprint, render_template, request, redirect, url_for, Response
from flask_login import login_required

from flask_website.chat.weibo import init_weibo_im, init_weibo_im_with_captcha
from flask_website.im import xiaoice_storage

xiaoice = Blueprint('xiaoice', __name__)

logger = logging.getLogger('admin.xiaoice')

@xiaoice.route('/index')
@login_required
def index():
    return render_template('admin/xiaoice/index.html', free_xiaoice=xiaoice_storage.get_free_xiaoice(), work_xiaoice=xiaoice_storage.get_work_xiaoice())


@xiaoice.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    if request.method == 'GET':
        return render_template('admin/xiaoice/add.html')

    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        Thread(target=_handle_add_xiaoice(username, password)).start()
        return redirect(url_for('xiaoice.index'))


@xiaoice.route('/get_captcha', methods=['GET'])
@login_required
def get_captcha():
    username = request.args.get('username')
    xiaoice = xiaoice_storage.get_xiaoice_by_username(username)
    if not xiaoice.is_login and xiaoice.need_captcha:
        return render_template('admin/xiaoice/captcha_dialog.html', username=username)


@xiaoice.route('/show_captcha', methods=['GET'])
@login_required
def show_captcha():
    username = request.args.get('username')
    xiaoice = xiaoice_storage.get_xiaoice_by_username(username)
    return Response(xiaoice.get_captcha(), mimetype='image/jpeg')


@xiaoice.route('/input_captcha', methods=['POST'])
@login_required
def input_captcha():
    username = request.form['username']
    captcha = request.form['captcha']
    Thread(target=_handle_input_captcha(username, captcha)).start()
    return redirect(url_for('xiaoice.index'))


def _handle_input_captcha(username, captcha):
    weibo = xiaoice_storage.get_xiaoice_by_username(username).weibo
    init_weibo_im_with_captcha(weibo, captcha)


def _handle_add_xiaoice(username, password):
    weibo = init_weibo_im(username, password)
    logger.debug('add Weibo username: %s to xiaoice storage' % username)
    xiaoice_storage.add_xiaoice(weibo)

flask_website/templates/chat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chat</title>
    <link href="{{url_for('static', filename='bootstrap-3.3.7/css/bootstrap.css') }}" rel="stylesheet" media="screen">
    <link href="{{url_for('static', filename='css/chat.css') }}" rel="stylesheet" media="screen">
    <script src="{{url_for('static', filename='js/jquery-2.1.1.min.js') }}"></script>
</head>
<body>

<div class="container">
    <div class="chat">
        <div class="chat-history">
            <ul class="chat-ul">
            </ul>
        </div> <!-- end chat-history -->
    </div> <!-- end chat -->
</div>
<div class="navbar-fixed-bottom">
    <div class="container">
        <div class="msg-input input-group input-group-lg">
            <input id="msg-content" type="text" class="form-control" onkeydown="if(event.keyCode==13) send_msg();" placeholder="press Enter to send" aria-describedby="sizing-addon1">
            <span class="input-group-btn">
                <button id="send-msg" class="btn btn-default" type="button">Send!</button>
            </span>
        </div>
    </div>
</div>
</body>
<script type="application/javascript">

    var polling_id = 0;
    $(document).ready(function () {
        $('#send-msg').click(send_msg);
        handshake();
    });

    function send_msg(){
        var msg = get_input_msg();
        if(msg){
            send(msg);
        }
    }

    function handshake(){
        $.ajax({
            url:'{{ url_for('chat.handshake') }}',
            type:'POST',
            contentType:'application/json',
            success:function(data){
                if(data.retCode >= 0){
                    polling_msg()
                }
                show_receive_msg(data.msg)
            },
            error:function (XMLHttpRequest, textStatus, errorThrown) {
                console.log(XMLHttpRequest.status);
                console.log(XMLHttpRequest.readyState);
                console.log(textStatus);
            }
        });
    }

    function get_input_msg(){
        return $('#msg-content').val();
    }

    function clear_input_msg() {
        $('#msg-content').val('');
    }
    
    function screen_down() {
        var h = $(document).height()-$(window).height();
        $(document).scrollTop(h);
    }

    function send(msg) {
        var data = {'msg':msg};
        $.ajax({
            url:'{{ url_for('chat.message') }}',
            type:'POST',
            contentType:'application/json',
            data:JSON.stringify(data),
            success:function(data){
                if(data.retCode == '0'){
                    show_send_msg(msg);
                    clear_input_msg();
                    screen_down();
                }
            },
            error:function (XMLHttpRequest, textStatus, errorThrown) {
                console.log(XMLHttpRequest.status);
                console.log(XMLHttpRequest.readyState);
                console.log(textStatus);
            }
        });
    }

    function polling_msg(){
        var data = {'id':polling_id};
        $.ajax({
            url:'{{ url_for('chat.im') }}',
            type:'POST',
            contentType:'application/json',
            data:JSON.stringify(data),
            success:function (data) {
                if(data.retCode == '0'){
                    if(data.msg != null){
                        show_receive_msg(data.msg);
                    }
                }
                polling_msg()
            },
            error:function (XMLHttpRequest, textStatus, errorThrown) {
                console.log(XMLHttpRequest.status);
                console.log(XMLHttpRequest.readyState);
                console.log(textStatus);
            }
        });
        polling_id++;
    }

    function show_send_msg(msg){
        var html = '<li class="clearfix">\
                        <div class="message-data align-right">\
                            <span class="message-data-name"><img src="{{url_for('static', filename='img/headimg_visitor.jpg') }}" class="head-img img-rounded" /></span> <i class="fa fa-circle me"></i>\
                            </div>\
                            <div class="message me-message float-right">' + msg + '</div>\
                    </li>';
        $('.chat-ul').append(html);
    }

    function show_receive_msg(msg){
        var html = '<li>\
                        <div class="message-data">\
                        <span class="message-data-name"><i class="fa fa-circle you"></i><img src="{{url_for('static', filename='img/headimg_xiaoice.jpg') }}" class="head-img img-rounded" /></span>\
                        </div>\
                        <div class="message you-message">' + msg + '</div>\
                    </li>';
        $('.chat-ul').append(html);
    }

</script>
</html>

flask_website/templates/layouts/alert_message.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}